### PR TITLE
Validate the API requests made using Environment keys 

### PR DESCRIPTION
**Pull request by prachidamle**
Fix authTokenValidator filter to authorize requests made using Environment keys.

Removing the check that was preventing the validation of env keys, I am not sure what was the purpose of this check originally.

@cjellick  pls. review

### CODE REVIEW

**Comment by cjellick** [comment]
LGTM

**Comment by cjellick** [comment]
but build failed, so we need to figure that out

**Comment by prachidamle** [comment]
build failed because of this golint issue https://github.com/golang/lint/issues/400
Need to update golang version

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
